version: '3'

services: 
  texlive:
    image: 'jumpaku/texlive-docker'
    working_dir: '/workdir/'
    command: ['latexmk', '-pvc']
    volumes: 
      - './proceedings/:/workdir/'
      - './.latexmkrc:/root/.latexmkrc:ro'