version: '3'

services: 
  texlive:
    image: 'jumpaku/texlive-docker'
    working_dir: '/workdir/'
    command: ["sleep", "infinity"]
    volumes: 
      - './../:/workdir/'
      - './.latexmkrc:/root/.latexmkrc:ro'